base: &base
  do_not_reply: donotreply@prayerthread.org

development:
  <<: *base
  domain: localhost:3000

test:
  <<: *base
  domain: test.host

production:
  <<: *base
  domain: prayerthread.heroku.com
