defaults: &defaults
  host: prayerthread.local
  mail:
    from: prayerthread.org <notifications@prayerthread.org>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  host: prayerthread.org
